### ISSUE TITLE
Failure to sort the last few items

### ISSUE THREAD

**Issue by DevinR528** [DevinR528/toml-parse#3]
This table fails to sort the last 2 items
```toml
[dev-dependencies]
cargo_metadata = "0.9.0"
compiletest_rs = { version = "0.4.0", features = ["tmp"] }
tester = "0.7"
lazy_static = "1.0"
clippy-mini-macro-test = { version = "0.2", path = "mini-macro" }
serde = { version = "1.0", features = ["derive"] }
derive-new = "0.5"

# A noop dependency that changes in the Rust repository, it's a bit of a hack.
# See the `src/tools/rustc-workspace-hack/README.md` file in `rust-lang/rust`
# for more information.
rustc-workspace-hack = "1.0.0"
```
